[package]
name        = "remote"
version     = "1.0.0"
description = "Generate remote repo URLs"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "WTFPL OR MIT OR Apache-2.0"
repository  = "https://github.com/casey/remote"

[dependencies]
clap = "^2.20.1"
